# Generated by Django 5.2 on 2025-04-14 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Client',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
    ]
