# Generated by Django 5.2 on 2025-04-26 21:41

import real_estate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_rename_userprofile_client_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('B', 'Buyer'), ('S', 'Seller'), ('A', 'Admin')], default='B', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='real_estate/images', validators=[real_estate.validators.validate_image_size]),
        ),
    ]
