# Generated by Django 5.2 on 2025-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_alter_property_options_alter_client_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land')], default='house', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for sale', 'For Sale'), ('sold', 'Sold'), ('pending', 'Pending')], default='for sale', max_length=20),
        ),
    ]
