# Generated by Django 5.2.1 on 2025-05-24 12:34

import real_estate.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_alter_property_property_type_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', validators=[real_estate.validators.validate_image_size]),
        ),
    ]
